from auto_service_management.auto_service_management.reporting.types import ReportDefinition, column

CONTROL_REPORTS = {
	"Customer LPO Utilization": ReportDefinition(
		source_doctype="Customer LPO",
		permission_doctype="Customer LPO",
		columns=(
			column("LPO", "name", "Link", "Customer LPO"),
			column("External LPO", "lpo_number"),
			column("Customer", "customer", "Link", "Customer"),
			column("Issue Date", "issue_date", "Date"),
			column("Expiry Date", "expiry_date", "Date"),
			column("Status", "status"),
			column("Basis", "ceiling_basis"),
			column("Effective Authority", "effective_authorized_amount", "Currency"),
			column("Invoiced", "invoiced_amount", "Currency"),
			column("Remaining", "remaining_amount", "Currency"),
			column("Vehicles", "vehicle_count", "Int"),
			column("Completed", "completed_vehicle_count", "Int"),
		),
		fields=(
			"name",
			"lpo_number",
			"customer",
			"issue_date",
			"expiry_date",
			"status",
			"ceiling_basis",
			"effective_authorized_amount",
			"invoiced_amount",
			"remaining_amount",
			"vehicle_count",
			"completed_vehicle_count",
		),
		filters=("customer", "status", "ceiling_basis"),
		date_field="issue_date",
		order_by="issue_date desc, modified desc",
	),
	"Customer LPO Vehicle Progress": ReportDefinition(
		source_doctype="Customer LPO Vehicle",
		permission_doctype="Customer LPO",
		permission_parent_doctype="Customer LPO",
		child_parent_doctype="Customer LPO",
		columns=(
			column("LPO", "parent", "Link", "Customer LPO"),
			column("Registration", "registration_number"),
			column("Customer Vehicle", "customer_vehicle", "Link", "Customer Vehicle"),
			column("Repair Job", "repair_job", "Link", "Repair Job"),
			column("Requested Work", "requested_work", "Small Text"),
			column("Planned Date", "planned_date", "Date"),
			column("Status", "status"),
		),
		fields=(
			"parent",
			"registration_number",
			"customer_vehicle",
			"repair_job",
			"requested_work",
			"planned_date",
			"status",
		),
		filters=("parent", "customer_vehicle", "repair_job", "status"),
		date_field="planned_date",
		order_by="planned_date asc, parent asc, idx asc",
	),
	"Repair Revenue by Period": ReportDefinition(
		source_doctype="Repair Job Invoice Row",
		permission_doctype="Repair Job",
		parent_field="repair_job",
		permission_parent_doctype="Repair Job",
		child_parent_doctype="Repair Job",
		columns=(
			column("Closed On", "closed_on", "Datetime", width=170),
			column("Repair Job", "repair_job", "Link", "Repair Job"),
			column("Customer", "customer", "Link", "Customer"),
			column("Sales Invoice", "sales_invoice", "Link", "Sales Invoice"),
			column("Revenue", "grand_total", "Currency"),
		),
		fields=("closed_on", "repair_job", "customer", "sales_invoice", "grand_total"),
		filters=("customer", "sales_invoice"),
		base_filters={"job_status": "Closed"},
		date_field="closed_on",
		order_by="closed_on desc, repair_job desc, sales_invoice desc",
	),
	"Gate Pass Register": ReportDefinition(
		source_doctype="Gate Pass",
		permission_doctype="Gate Pass",
		columns=(
			column("Gate Pass", "name", "Link", "Gate Pass"),
			column("Repair Job", "repair_job", "Link", "Repair Job"),
			column("Vehicle", "customer_vehicle", "Link", "Customer Vehicle"),
			column("Status", "status"),
			column("Issued", "issue_date", "Datetime", width=170),
			column("Used", "use_date", "Datetime", width=170),
		),
		fields=("name", "repair_job", "customer_vehicle", "status", "issue_date", "use_date"),
		filters=("repair_job", "customer_vehicle", "status"),
		date_field="issue_date",
		order_by="issue_date desc, modified desc",
	),
	"Corporate Credit Releases": ReportDefinition(
		source_doctype="Repair Job Invoice Row",
		permission_doctype="Repair Job",
		parent_field="repair_job",
		permission_parent_doctype="Repair Job",
		child_parent_doctype="Repair Job",
		columns=(
			column("Repair Job", "repair_job", "Link", "Repair Job"),
			column("Customer", "customer", "Link", "Customer"),
			column("Invoice", "sales_invoice", "Link", "Sales Invoice"),
			column("Payment Status", "payment_status"),
			column("Closed On", "closed_on", "Datetime", width=170),
		),
		fields=("repair_job", "customer", "sales_invoice", "payment_status", "closed_on"),
		filters=("customer", "sales_invoice"),
		base_filters={
			"job_status": "Closed",
			"payment_status": ["!=", "Paid"],
		},
		date_field="closed_on",
		order_by="closed_on desc, repair_job desc, sales_invoice desc",
	),
	"Discount and Price Change Audit": ReportDefinition(
		source_doctype="Version",
		permission_doctype="Repair Job",
		parent_field="docname",
		columns=(
			column("Changed On", "modified", "Datetime", width=170),
			column("Repair Job", "docname", "Link", "Repair Job"),
			column("Changed By", "owner", "Link", "User"),
			column("Changes", "data", "Long Text", width=420),
		),
		fields=("modified", "docname", "owner", "data"),
		filters=("docname", "owner"),
		base_filters={"ref_doctype": "Repair Job", "data": ["like", "%rate%"]},
		date_field="modified",
		order_by="modified desc",
	),
}
