from frappe.utils import now_datetime
from pypika import Field
from pypika import functions as pypika_functions

from auto_service_management.auto_service_management.reporting.types import ReportDefinition, column

WORKSHOP_REPORTS = {
	"Open Repair Jobs": ReportDefinition(
		source_doctype="Repair Job",
		permission_doctype="Repair Job",
		columns=(
			column("Repair Job", "name", "Link", "Repair Job"),
			column("Customer", "customer", "Link", "Customer"),
			column("Vehicle", "customer_vehicle", "Link", "Customer Vehicle"),
			column("Status", "job_status"),
			column("Bay", "workshop_bay", "Link", "Workshop Bay"),
			column("Promised Date", "promised_date", "Datetime", width=170),
		),
		fields=("name", "customer", "customer_vehicle", "job_status", "workshop_bay", "promised_date"),
		filters=("customer", "customer_vehicle", "job_status", "workshop_bay", "priority"),
		base_filters={"job_status": ["not in", ["Closed", "Cancelled"]]},
		order_by="promised_date asc, modified desc",
	),
	"Daily Workshop Load": ReportDefinition(
		source_doctype="Repair Job",
		permission_doctype="Repair Job",
		columns=(
			column("Repair Job", "name", "Link", "Repair Job"),
			column("Status", "job_status"),
			column("Bay", "workshop_bay", "Link", "Workshop Bay"),
			column("Priority", "priority"),
			column("Promised Date", "promised_date", "Datetime", width=170),
		),
		fields=("name", "job_status", "workshop_bay", "priority", "promised_date"),
		filters=("workshop_bay", "job_status", "priority"),
		base_filters={"job_status": ["not in", ["Closed", "Cancelled"]]},
		date_field="promised_date",
		order_by="promised_date asc, priority desc",
	),
	"Jobs by Status": ReportDefinition(
		source_doctype="Repair Job",
		permission_doctype="Repair Job",
		columns=(column("Status", "job_status"), column("Jobs", "job_count", "Int", width=100)),
		fields=("job_status", {"COUNT": "name", "as": "job_count"}),
		filters=("customer", "workshop_bay"),
		date_field="creation",
		group_by="job_status",
		order_by="job_count desc, job_status asc",
	),
	"Jobs Waiting for Parts": ReportDefinition(
		source_doctype=("Repair Job Service Part", "Repair Job Service Consumable"),
		permission_doctype="Repair Job",
		parent_field="repair_job",
		columns=(
			column("Repair Job", "repair_job", "Link", "Repair Job"),
			column("Service", "repair_job_service", "Link", "Repair Job Service"),
			column("Item", "item_code", "Link", "Item"),
			column("Description", "description", width=220),
			column("Quantity", "quantity", "Float"),
			column("Status", "status"),
		),
		fields=("repair_job", "repair_job_service", "item_code", "description", "quantity", "status"),
		filters=("item_code", "status"),
		base_filters={"status": ["in", ["Pending Approval", "Approved"]]},
		order_by="repair_job asc, idx asc",
	),
	"Technician Productivity": ReportDefinition(
		source_doctype="Repair Job Service Labour",
		permission_doctype="Repair Job",
		parent_field="repair_job",
		columns=(
			column("Technician", "assigned_to", "Link", "User"),
			column("Jobs", "job_count", "Int"),
			column("Estimated Hours", "estimated_hours", "Float"),
			column("Actual Hours", "actual_hours", "Float"),
		),
		fields=(
			"assigned_to",
			pypika_functions.Count(Field("repair_job")).distinct().as_("job_count"),
			{"SUM": "estimated_hours", "as": "estimated_hours"},
			{"SUM": "actual_hours", "as": "actual_hours"},
		),
		filters=("assigned_to",),
		base_filters={"assigned_to": ["is", "set"]},
		group_by="assigned_to",
		order_by="actual_hours desc, assigned_to asc",
	),
	"Labour Hours by Technician": ReportDefinition(
		source_doctype="Repair Job Service Labour",
		permission_doctype="Repair Job",
		parent_field="repair_job",
		columns=(
			column("Technician", "assigned_to", "Link", "User"),
			column("Actual Hours", "actual_hours", "Float"),
		),
		fields=("assigned_to", {"SUM": "actual_hours", "as": "actual_hours"}),
		filters=("assigned_to",),
		base_filters={"assigned_to": ["is", "set"]},
		group_by="assigned_to",
		order_by="actual_hours desc, assigned_to asc",
	),
	"Parts Used by Repair Job": ReportDefinition(
		source_doctype=("Repair Job Service Part", "Repair Job Service Consumable"),
		permission_doctype="Repair Job",
		parent_field="repair_job",
		columns=(
			column("Repair Job", "repair_job", "Link", "Repair Job"),
			column("Service", "repair_job_service", "Link", "Repair Job Service"),
			column("Item", "item_code", "Link", "Item"),
			column("Description", "description", width=220),
			column("Quantity", "quantity", "Float"),
			column("Amount", "amount", "Currency"),
		),
		fields=("repair_job", "repair_job_service", "item_code", "description", "quantity", "amount"),
		filters=("repair_job", "item_code"),
		base_filters={"status": "Completed"},
		order_by="repair_job desc, idx asc",
	),
	"Vehicle Service History": ReportDefinition(
		source_doctype="Service History",
		permission_doctype="Service History",
		columns=(
			column("Vehicle", "customer_vehicle", "Link", "Customer Vehicle"),
			column("Repair Job", "repair_job", "Link", "Repair Job"),
			column("Closure Date", "closure_date", "Date"),
			column("Odometer", "odometer_at_closure", "Float"),
			column("Total", "total_amount", "Currency"),
		),
		fields=("customer_vehicle", "repair_job", "closure_date", "odometer_at_closure", "total_amount"),
		filters=("customer_vehicle", "repair_job"),
		date_field="closure_date",
		order_by="closure_date desc, modified desc",
	),
	"Delayed Jobs": ReportDefinition(
		source_doctype="Repair Job",
		permission_doctype="Repair Job",
		columns=(
			column("Repair Job", "name", "Link", "Repair Job"),
			column("Customer", "customer", "Link", "Customer"),
			column("Status", "job_status"),
			column("Promised Date", "promised_date", "Datetime", width=170),
		),
		fields=("name", "customer", "job_status", "promised_date"),
		filters=("customer", "job_status"),
		base_filters={
			"promised_date": ["<", now_datetime()],
			"job_status": ["not in", ["Closed", "Cancelled"]],
		},
		order_by="promised_date asc, modified desc",
	),
}
